name       : glfw
version    : 3.1.2
release    : 4
source     :
    - https://github.com/glfw/glfw/archive/3.1.2.tar.gz : 6ac642087682aaf7f8397761a41a99042b2c656498217a1c63ba9706d1eef122
license    : BSD-3-Clause
summary    : A multi-platform library for OpenGL, window and input.
description: |
    A multi-platform library for OpenGL, window and input.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
