name       : glfw
version    : 3.3.4
release    : 9
source     :
    - https://github.com/glfw/glfw/archive/3.3.4.tar.gz : cc8ac1d024a0de5fd6f68c4133af77e1918261396319c24fd697775a6bc93b63
license    : zlib-acknowledgement
component  : programming
summary    : A multi-platform library for OpenGL, OpenGL ES and Vulkan, window and input.
description: |
    A multi-platform library for OpenGL, OpenGL and Vulkan development on the desktop. It provides a simple API for creating windows, contexts and surfaces, receiving input and events.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xi)
rundeps    :
    - libxcursor
    - libxinerama
    - libxrandr
    - libxxf86vm
    - libxi
    - devel:
        - libxcursor-devel
        - libxinerama-devel
        - libxrandr-devel
        - libxxf86vm-devel
        - libxi-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
