name       : glfw
version    : 3.1.1
release    : 3
source     :
    - https://github.com/glfw/glfw/archive/3.1.1.tar.gz : 4de311ec9bf43bfdc8423ddf93b91dc54dc73dcfbedfb0991b6fbb3a9baf245f
license    : BSD-3-Clause
summary    : A multi-platform library for OpenGL, window and input.
description: |
    A multi-platform library for OpenGL, window and input.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xrandr)
    - pkgconfig(xinerama)
    - pkgconfig(xcursor)
    - pkgconfig(glu)
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
